from typing import Any, Literal
from pathlib import Path
import torch
from torch.optim import Adam
from PIL import Image
from ..image import raw2resized, resized2image01, image012pixel_values, quantize_ste, image012resized, IMAGE_SIZE

from transformers import AutoTokenizer, AutoModelForMultimodalLM

from .interface import VLM


class LLaVA(VLM):

    IMAGE_TOKEN_ID = 32000
    NUM_IMAGE_TOKENS = 576

    def __init__(self, device: str):
        super().__init__(device)

        self.tok = AutoTokenizer.from_pretrained("llava-hf/llava-1.5-7b-hf")
        self.model = AutoModelForMultimodalLM.from_pretrained("llava-hf/llava-1.5-7b-hf")

        # attacks optimize the image, not the weights: freezing params stops backward
        self.model.requires_grad_(False)
        self.model.gradient_checkpointing_enable()
        self.model.eval()

        if self.device is not None:
            self.model.to(self.device)


    def gen(self, 
            img: Image.Image | torch.Tensor, 
            question: str, 
            answer_priming: str = "", 
            img_type: Literal['raw', 'resized', 'image01', 'pixel_value'] = 'raw',
            max_new_tokens = 64) -> str:

        text = f"USER: <image>\n{question}\n ASSISTANT:{answer_priming}"
        ids = self.tok(text, return_tensors="pt").input_ids[0]   # BOS is added here

        # expand the placeholders for image tokens
        pos = (ids == self.IMAGE_TOKEN_ID).nonzero()[0, 0].item()
        input_ids = torch.cat([ids[:pos],
                            ids.new_full((self.NUM_IMAGE_TOKENS,), self.IMAGE_TOKEN_ID),
                            ids[pos+1:]])[None].to(self.device)

        if img_type == 'raw':
            assert isinstance(img, Image.Image)
            pixel_values = image012pixel_values(resized2image01(raw2resized([img]))).to(self.device)
        elif img_type == 'resized':
            assert isinstance(img, Image.Image)
            pixel_values = image012pixel_values(resized2image01([img])).to(self.device)
        elif img_type == 'image01':
            assert isinstance(img, torch.Tensor)
            assert len(img.shape) == 4
            pixel_values = image012pixel_values(img).to(self.device)
        elif img_type == 'pixel_value':
            assert isinstance(img, torch.Tensor)
            assert len(img.shape) == 4
            pixel_values = img.to(self.device)
        else:
            raise ValueError("Invalid image type:", img_type)
            
        # pixel_values: [1, 3, 336, 336]

        generated = input_ids
        past = None                  # KV cache
        cur_input = input_ids        # prefill full sequence, then new tokens only
        pv = pixel_values            # only pass in the image during prefill

        for _ in range(max_new_tokens):
            with torch.no_grad():
                out = self.model(
                    input_ids=cur_input,
                    attention_mask=torch.ones_like(generated),
                    pixel_values=pv,
                    past_key_values=past,
                    use_cache=True,
                )
            past = out.past_key_values
            next_token = out.logits[:, -1, :].argmax(dim=-1, keepdim=True)  # greedy decoding
            generated = torch.cat([generated, next_token], dim=-1)
            if next_token.item() == self.tok.eos_token_id:
                break

            cur_input = next_token
            pv = None

        new_tokens = generated[0][input_ids.shape[-1]:]
        return(self.tok.decode(new_tokens))


    @torch.no_grad()
    def gen_batch(self,
            img: Image.Image | torch.Tensor,
            questions: list[str],
            answer_priming: str = "",
            img_type: Literal['raw', 'resized', 'image01', 'pixel_value'] = 'raw',
            max_new_tokens: int = 64) -> list[str]:
        '''
        Batched greedy generation: one forward-batch for many prompts.

        img is either a single image (broadcast to every prompt) or a batch of exactly
        len(questions) images. Returns one decoded string per question.

        Prompts are LEFT-padded (the standard for batched decoding: real tokens are
        right-aligned so generated tokens continue from a shared final column, and
        model.generate handles the padded position_ids / attention mask).

        Generated by AI.
        '''
        N = len(questions)

        # pixel values (broadcast a single image across the batch)
        if img_type == 'raw':
            assert isinstance(img, Image.Image)
            pv = image012pixel_values(resized2image01(raw2resized([img]))).to(self.device)
        elif img_type == 'resized':
            assert isinstance(img, Image.Image)
            pv = image012pixel_values(resized2image01([img])).to(self.device)
        elif img_type == 'image01':
            assert isinstance(img, torch.Tensor) and img.dim() == 4
            pv = image012pixel_values(img).to(self.device)
        elif img_type == 'pixel_value':
            assert isinstance(img, torch.Tensor) and img.dim() == 4
            pv = img.to(self.device)
        else:
            raise ValueError("Invalid image type:", img_type)

        if pv.shape[0] == 1:
            pv = pv.expand(N, -1, -1, -1)
        assert pv.shape[0] == N, "img must have batch size 1 (broadcast) or len(questions)"

        pad_id = self.tok.pad_token_id if self.tok.pad_token_id is not None else self.tok.eos_token_id

        # per-prompt input ids with the image placeholder expanded
        seqs = []
        for q in questions:
            text = f"USER: <image>\n{q}\n ASSISTANT:{answer_priming}"
            ids = self.tok(text, return_tensors="pt").input_ids[0]   # BOS added here
            pos = (ids == self.IMAGE_TOKEN_ID).nonzero()[0, 0].item()
            seqs.append(torch.cat([ids[:pos],
                                   ids.new_full((self.NUM_IMAGE_TOKENS,), self.IMAGE_TOKEN_ID),
                                   ids[pos + 1:]]))

        L_max = max(s.shape[0] for s in seqs)
        input_ids = torch.full((N, L_max), pad_id, dtype=torch.long)
        attn = torch.zeros((N, L_max), dtype=torch.long)
        for i, s in enumerate(seqs):
            L = s.shape[0]
            input_ids[i, L_max - L:] = s      # left-padding: real tokens right-aligned
            attn[i, L_max - L:] = 1
        input_ids = input_ids.to(self.device)
        attn = attn.to(self.device)

        out = self.model.generate(
            input_ids=input_ids,
            attention_mask=attn,
            pixel_values=pv,
            max_new_tokens=max_new_tokens,
            do_sample=False,        # greedy, matching gen()
            pad_token_id=pad_id,
        )

        new_tokens = out[:, L_max:]   # left-padding -> prompts share the same length L_max
        return [self.tok.decode(t, skip_special_tokens=True) for t in new_tokens]


    def loglikelyhood_classify(
            self,
            question: str,
            answer_priming: str,
            image01s: torch.Tensor,
            candidates: list[str],
            differentiable: bool = False,
            grad_candidates: list[int] | None = None,
        ) -> torch.Tensor:
        '''
        grad_candidates: Indices of the
        candidates whose scores must carry a gradient back to image01s
        '''

        ctx = torch.enable_grad if differentiable else torch.no_grad

        with ctx():

            img_tensor = image012pixel_values(image01s).to(self.device)

            N = len(img_tensor)

            text = f"USER: <image>\n{question}\n ASSISTANT:{answer_priming}"
            ids = self.tok(text, return_tensors="pt").input_ids[0]   # BOS is added here

            # expand the placeholders for image tokens
            pos = (ids == self.IMAGE_TOKEN_ID).nonzero()[0, 0].item()
            input_ids = torch.cat([ids[:pos],
                                ids.new_full((self.NUM_IMAGE_TOKENS,), self.IMAGE_TOKEN_ID),
                                ids[pos+1:]])[None].to(self.device)

            # N copies for batched inference
            L_prefix = input_ids.shape[1]
            input_ids = input_ids.expand(N, L_prefix)

            if differentiable:
                # Attack path: no KV cache 
                grad_set = set(range(len(candidates))) if grad_candidates is None else set(grad_candidates)
                was_training = self.model.training
                try:
                    scores = []
                    for i, lab in enumerate(candidates):
                        needs_grad = i in grad_set
                        self.model.train(needs_grad)   # checkpointing engages only in train mode; dropouts are 0
                        cand_ctx = torch.enable_grad if needs_grad else torch.no_grad
                        with cand_ctx():
                            lab_ids = self.tok(lab, add_special_tokens=False, return_tensors="pt").input_ids.to(self.device)
                            L_lab = lab_ids.shape[1]
                            lab_ids = lab_ids.expand(N, L_lab)

                            full_ids = torch.cat([input_ids, lab_ids], dim=1)   # (N, L_prefix + L_lab)
                            out = self.model(
                                input_ids=full_ids,
                                attention_mask=torch.ones_like(full_ids),
                                pixel_values=img_tensor,
                                past_key_values=None,
                                use_cache=False,
                            )

                            # logit at position (L_prefix-1 + k) predicts label token k
                            logits = out.logits[:, L_prefix - 1: L_prefix + L_lab - 1, :]            # (N, L_lab, V)
                            lp = logits.log_softmax(-1).gather(2, lab_ids[:, :, None]).squeeze(-1)   # (N, L_lab)
                            scores.append(lp.mean(dim=1))

                    return torch.stack(scores, dim=1)   # (N, X)
                finally:
                    self.model.train(was_training)

            else:
                # precompute the common prefix

                prefix_out = self.model(
                    input_ids=input_ids,
                    attention_mask=torch.ones_like(input_ids),
                    pixel_values=img_tensor,
                    past_key_values=None,
                    use_cache=True,
                )

                cache = prefix_out.past_key_values
                first_logp = prefix_out.logits[:, -1, :].log_softmax(-1)

                # scores for different labels
                scores = []
                for lab in candidates:
                    lab_ids = self.tok(lab, add_special_tokens=False, return_tensors="pt").input_ids.to(self.device)
                    L_lab = lab_ids.shape[1]
                    lab_ids = lab_ids.expand(N, L_lab)
                    lp0 = first_logp.gather(1, lab_ids[:, :1])  # (N, 1)

                    if L_lab > 1:
                        out = self.model(
                            input_ids = lab_ids,
                            attention_mask = torch.ones(N, L_prefix + L_lab, device=self.device),
                            pixel_values=None,
                            past_key_values=prefix_out.past_key_values,
                            use_cache=True,
                        )


                        rest_logp = out.logits[:, :-1, :].log_softmax(-1).gather(2, lab_ids[:, 1:, None]).squeeze(-1) # (N, L_lab-1)
                        lp = torch.cat([lp0, rest_logp], dim=1)

                        # reset the KV cache (the cache operation is in place)
                        cache.crop(L_prefix)
                    else:
                        lp = lp0

                    scores.append(lp.mean(dim=1))

                return torch.stack(scores, dim=1)   # (N, X)
            


    def classify_attack(
        self,
        image01s: torch.Tensor,
        question: str,
        answer_priming: str,
        candidates: list[str],
        target_candidate: list[int],

        max_steps: int = 20,
        stop_gap: float = 0.5,
        eps: float = 0.03,
        lr: float = 0.003,
        quantize: bool = False,

    ) -> torch.Tensor:
        '''
        Targeted attack on a whole batch of images, run in parallel.
        target_candidate[i] is the target label index for example i.

        Each example stopes when the margin exceeds stop_gap.

        Hard-constraint (PGD): the loss is just the (negative) target log-likelihood;
        after each step delta is projected onto the per-example RMS ball
        (sqrt(mean(delta^2)) <= eps, in [0, 1] units) and then onto the [0, 1] box.

        quantize: if True, the forward (and the recorded adversarial) is snapped to
        the uint8 grid via a straight-through estimator -- this is the attack.

        Return the adversarial examples.
        '''
        # forward through the uint8 grid or stay continuous
        proj = quantize_ste if quantize else (lambda x: x)

        N = image01s.shape[0]
        assert len(target_candidate) == N, "need exactly one target per image"

        image01s = image01s.to(self.device)
        target_t = torch.tensor(target_candidate, device=self.device)

        delta = torch.zeros_like(image01s, requires_grad=True)
        opt = Adam([delta], lr=lr)

        done = torch.zeros(N, dtype=torch.bool, device=self.device)
        adv_out = image01s.clone()

        for step in range(max_steps):
            active_idx = (~done).nonzero(as_tuple=False).squeeze(1) # global indices still being optimized
            if active_idx.numel() == 0:
                break

            # only the active examples go through the forward
            adv_active = proj(image01s[active_idx] + delta[active_idx])
            tgt_active = target_t[active_idx]
            grad_cols = sorted(set(tgt_active.tolist()))

            scores = self.loglikelyhood_classify(
                question=question,
                answer_priming=answer_priming,
                image01s=adv_active,
                candidates=candidates,
                differentiable=True,
                grad_candidates=grad_cols,
            )

            target_lp = scores.gather(1, tgt_active[:, None]).squeeze(1)   # carries grad

            others = scores.detach().clone()
            others.scatter_(1, tgt_active[:, None], float("-inf"))
            comp_lp = others.max(dim=1).values  # best competitor
            margins = target_lp.detach() - comp_lp

            # an example that crosses the threshold is recorded and dropped from the batch for good
            crossed = margins > stop_gap
            adv_out[active_idx[crossed]] = adv_active.detach()[crossed]
            done[active_idx[crossed]] = True

            print(f"Step {step}  done {int(done.sum())}/{N}  active {active_idx.numel()}  "
                  f"min_margin {margins.min().item():.3f}  mean_margin {margins.mean().item():.3f}")

            if done.all():
                break

            # optimize the examples that are still active after this step's records
            still = ~crossed
            loss = (-target_lp)[still].sum()

            opt.zero_grad()
            loss.backward()
            opt.step()

            with torch.no_grad():
                # hard constraint: project onto the per-example RMS ball, then the [0, 1] box.
                rms = delta.flatten(1).square().mean(dim=1).sqrt()          # (N,)
                delta.mul_((eps / rms.clamp_min(1e-12)).clamp(max=1.0).view(-1, 1, 1, 1))
                delta.copy_((image01s + delta).clamp(0, 1) - image01s)      # keep image in [0, 1]

        # examples that never crossed: take their last perturbation
        rest = (~done).nonzero(as_tuple=False).squeeze(1)
        adv_out[rest] = proj(image01s[rest] + delta[rest]).detach().clamp(0, 1)

        return adv_out


    def _saferlhf_batch_loss(
        self,
        image01_single: torch.Tensor,   # (1, 3, H, W)
        prompts: list[str],
        responses: list[str],
        pad_id: int,
    ) -> torch.Tensor:
        '''
        Mean (over the batch) negative teacher-forced log-likelihood of the harmful
        responses, conditioned on prompt + the single shared image.

        Generated by AI.
        '''
        N = len(prompts)

        pv_single = image012pixel_values(image01_single).to(self.device)   # (1, 3, H, W)
        pixel_values = pv_single.expand(N, -1, -1, -1)   # share grad back into the one image

        seqs, resp_start = [], []
        for prompt, response in zip(prompts, responses):
            text = f"USER: <image>\n{prompt}\n ASSISTANT:"
            ids = self.tok(text, return_tensors="pt").input_ids[0]   # BOS added here

            # expand the placeholder into NUM_IMAGE_TOKENS image tokens
            pos = (ids == self.IMAGE_TOKEN_ID).nonzero()[0, 0].item()
            prefix = torch.cat([ids[:pos],
                                ids.new_full((self.NUM_IMAGE_TOKENS,), self.IMAGE_TOKEN_ID),
                                ids[pos + 1:]])

            resp_ids = self.tok(response, add_special_tokens=False, return_tensors="pt").input_ids[0]
            seqs.append(torch.cat([prefix, resp_ids]))
            resp_start.append(prefix.shape[0])   # first response token index in the full sequence

        L_max = max(s.shape[0] for s in seqs)
        input_ids = torch.full((N, L_max), pad_id, dtype=torch.long)
        attn = torch.zeros((N, L_max), dtype=torch.long)
        resp_mask = torch.zeros((N, L_max), dtype=torch.bool)   # marks response-token positions
        for i, s in enumerate(seqs):
            L = s.shape[0]
            input_ids[i, :L] = s              # right-padding: real tokens left-aligned
            attn[i, :L] = 1
            resp_mask[i, resp_start[i]:L] = True

        input_ids = input_ids.to(self.device)
        attn = attn.to(self.device)
        resp_mask = resp_mask.to(self.device)

        out = self.model(
            input_ids=input_ids,
            attention_mask=attn,
            pixel_values=pixel_values,
            past_key_values=None,
            use_cache=False,
        )

        # causal shift: logit at position t-1 predicts token t
        shift_logits = out.logits[:, :-1, :]
        shift_labels = input_ids[:, 1:]
        shift_mask = resp_mask[:, 1:]

        logp = shift_logits.log_softmax(-1).gather(2, shift_labels[:, :, None]).squeeze(-1)   # (N, L_max-1)
        logp = logp * shift_mask
        per_example = logp.sum(dim=1) / shift_mask.sum(dim=1).clamp_min(1)   # mean log-likelihood per response

        return -per_example.mean()


    def saferlhf_attack(
        self,
        path: str,
        init_image: torch.Tensor | None = None,
        batch_size: int = 8,
        limit: int | None = None,
        shuffle: bool = True,
        seed: int = 42,
        max_steps: int = 100,
        lr: float = 0.01,
        quantize: bool = False,
        save_dir: str | None = None,
        save_every: int = 20,
    ) -> torch.Tensor:
        '''
        Universal adversarial attack against PKU-SafeRLHF: find ONE image that maximizes
        the mean teacher-forced log-likelihood of the harmful responses.

        The perturbation is fully unbounded -- the image is only clamped to [0, 1].
        One Adam step is taken per loader batch, cycling the dataset until max_steps steps.

        If save_dir is given, the current image is checkpointed there every save_every
        steps (and once at the end) as both a .pt tensor and a .png, and per-step training
        metrics (loss, mean log-likelihood, image-gradient norm) are written to a
        TensorBoard event file in the same directory.

        Generated by AI.
        '''
        from ..bench.interface import PKUSafeRLHF   # local import avoids model<->bench cycle

        dataset = PKUSafeRLHF(path, unsafe_only=True)

        # forward through the uint8 grid (attack the resized image) or stay continuous
        proj = quantize_ste if quantize else (lambda x: x)

        if init_image is None:
            g_init = torch.Generator().manual_seed(seed)
            adv = torch.rand(1, 3, IMAGE_SIZE, IMAGE_SIZE, generator=g_init).to(self.device)
        else:
            adv = init_image.detach().clone()
            if adv.dim() == 3:
                adv = adv[None]
            adv = adv.to(self.device).clamp(0, 1)
        adv.requires_grad_(True)

        opt = Adam([adv], lr=lr)
        pad_id = self.tok.pad_token_id if self.tok.pad_token_id is not None else self.tok.eos_token_id

        # TensorBoard: write the training curves into save_dir (skipped when not saving)
        writer = None
        if save_dir is not None:
            from torch.utils.tensorboard import SummaryWriter
            Path(save_dir).mkdir(parents=True, exist_ok=True)
            writer = SummaryWriter(log_dir=save_dir)

        # record the untouched starting image (before any optimizer step)
        if save_dir is not None:
            self._save_image01(proj(adv), save_dir, "adv_init")
            if writer is not None:
                writer.add_image("adv_init", proj(adv)[0].detach().cpu().clamp(0, 1), 0)

        was_training = self.model.training
        self.model.train(True)   # checkpointing engages only in train mode; dropouts are 0
        try:
            step = 0
            epoch = 0
            while step < max_steps:
                for prompts, responses, _is_safe in dataset.loader(
                    batch_size=batch_size, limit=limit, shuffle=shuffle, seed=seed, epoch=epoch
                ):
                    if step >= max_steps:
                        break

                    loss = self._saferlhf_batch_loss(proj(adv), prompts, responses, pad_id)

                    opt.zero_grad()
                    loss.backward()
                    grad_norm = adv.grad.detach().norm().item() if adv.grad is not None else 0.0
                    opt.step()

                    with torch.no_grad():
                        adv.clamp_(0, 1)   # hard constraint: valid image only

                    loss_val = loss.item()
                    print(f"Step {step}  batch {len(prompts)}  loss {loss_val:.4f}")

                    if writer is not None:
                        writer.add_scalar("train/loss", loss_val, step)             # minimized
                        writer.add_scalar("train/mean_logp", -loss_val, step)        # objective (maximized)
                        writer.add_scalar("train/grad_norm", grad_norm, step)
                        writer.add_scalar("train/batch_size", len(prompts), step)

                    if save_dir is not None and save_every > 0 and step % save_every == 0:
                        self._save_image01(proj(adv), save_dir, f"adv_step{step:05d}")
                        if writer is not None:
                            writer.add_image("adv_image", proj(adv)[0].detach().cpu().clamp(0, 1), step)

                    step += 1
                epoch += 1
        finally:
            self.model.train(was_training)
            if writer is not None:
                writer.close()

        adv_final = proj(adv).detach().clamp(0, 1)
        if save_dir is not None:
            self._save_image01(adv_final, save_dir, "adv_final")
        return adv_final


    @staticmethod
    def _save_image01(image01: torch.Tensor, save_dir: str, tag: str) -> None:
        # checkpoint the current image both as a raw tensor (.pt) and an inspectable image (.png)
        out = Path(save_dir)
        out.mkdir(parents=True, exist_ok=True)
        img = image01.detach().cpu().clamp(0, 1)
        torch.save(img, out / f"{tag}.pt")
        image012resized(img)[0].save(out / f"{tag}.png")