"""
Aggregate the perturbation-budget sweep into a transfer-vs-budget curve.

Reads `results/budget/eval-<model>-eps<NNN>/results.json` and emits:
  - budget.csv           tidy table (model, eps, robust accuracy, attack success, n)
  - budget.tex           a pgfplots figure fragment, ready to \\input
  - a console summary

The quantity plotted is `accuracy_original` -- accuracy on the *true* label under
attack, i.e. how much of the model's correct behaviour survives. It is the
dependability-relevant reading: a deployment cares that perception still works,
not specifically that the attacker hit their chosen target class. The targeted
success rate (`accuracy_attack`) is carried in the CSV and drawn as a dashed
companion series, because the gap between the two says whether a failed targeted
attack still destroyed the prediction.

pgfplots (rather than a rendered PNG) so the figure inherits the paper's fonts
and needs no plotting dependency on the cluster.

Usage:
    python scripts/aggregate_budget.py [--results-dir results/budget]
                                       [--out results/budget/aggregate]
"""

import argparse
import json
import re
from pathlib import Path

DIR_RE = re.compile(r"^eval-(?P<model>[a-z]+)-eps(?P<eps>\d{3})$")

# plotted in this order; label and pgfplots style per model
SERIES = {
    "clip":  ("CLIP (white-box)", "black,      mark=*"),
    "llava": ("LLaVA (transfer)", "blue!70!black, mark=square*"),
    "rwkv":  ("VisualRWKV (transfer)", "red!70!black,  mark=triangle*"),
}


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--results-dir", default="results/budget", type=Path)
    ap.add_argument("--out", default="results/budget/aggregate", type=Path)
    args = ap.parse_args()

    rows = []
    for d in sorted(args.results_dir.glob("eval-*")):
        m = DIR_RE.match(d.name)
        if not m:
            continue
        if not (d / "DONE").exists():
            print(f" !! skipping {d.name}: no DONE marker")
            continue
        res = json.loads((d / "results.json").read_text())
        missing = [k for k in ("accuracy_original", "accuracy_attack") if k not in res]
        if missing:
            print(f" !! skipping {d.name}: missing {missing} "
                  "(is this an adversarial eval?)")
            continue
        # the eval summary does not record the example count; the attack that built
        # the dataset does, so read it from there
        attack_res = args.results_dir / f"clip-attack-eps{m.group('eps')}" / "results.json"
        n = None
        if attack_res.exists():
            n = json.loads(attack_res.read_text()).get("num_examples")

        rows.append({
            "model": m.group("model"),
            "eps": int(m.group("eps")) / 1000.0,
            "robust_acc": res["accuracy_original"],
            "attack_success": res["accuracy_attack"],
            "n": n,
        })

    if not rows:
        raise SystemExit(f"no completed budget evals found under {args.results_dir}")

    rows.sort(key=lambda r: (r["model"], r["eps"]))
    args.out.mkdir(parents=True, exist_ok=True)

    with (args.out / "budget.csv").open("w") as f:
        f.write("model,eps,robust_accuracy,attack_success,n\n")
        for r in rows:
            f.write(f"{r['model']},{r['eps']:.3f},{r['robust_acc']:.4f},"
                    f"{r['attack_success']:.4f},{r['n']}\n")

    print(f"\n{'model':<6} {'eps':>6} {'robust acc':>11} {'targeted succ':>14} {'n':>6}")
    print("-" * 47)
    for r in rows:
        print(f"{r['model']:<6} {r['eps']:6.3f} {r['robust_acc']:11.1%} "
              f"{r['attack_success']:14.1%} {r['n'] or '?':>6}")

    found = [m for m in SERIES if any(r["model"] == m for r in rows)]
    missing = [m for m in SERIES if m not in found]
    if missing:
        print(f"\n !! no data for {missing}; the figure will omit those series")

    tex = [
        "% generated by scripts/aggregate_budget.py -- do not edit by hand",
        "% needs \\usepackage{pgfplots} and \\pgfplotsset{compat=1.18} in the preamble",
        "\\begin{tikzpicture}",
        "\\begin{axis}[",
        "  width=\\columnwidth, height=0.62\\columnwidth,",
        "  xlabel={perturbation budget (RMS)}, ylabel={accuracy on true label},",
        "  xmin=0, ymin=0, ymax=1,",
        "  legend style={font=\\scriptsize, at={(0.98,0.98)}, anchor=north east, "
        "draw=none, fill opacity=0.8},",
        "  tick label style={font=\\scriptsize}, label style={font=\\small},",
        "  grid=major, grid style={gray!25},",
        "]",
    ]
    for model in found:
        label, style = SERIES[model]
        pts = " ".join(f"({r['eps']:.3f},{r['robust_acc']:.4f})"
                       for r in rows if r["model"] == model)
        tex.append(f"\\addplot[{style}, thick] coordinates {{{pts}}};")
        tex.append(f"\\addlegendentry{{{label}}}")
    for model in found:
        _, style = SERIES[model]
        pts = " ".join(f"({r['eps']:.3f},{r['attack_success']:.4f})"
                       for r in rows if r["model"] == model)
        tex.append(f"\\addplot[{style}, dashed, thin, forget plot] "
                   f"coordinates {{{pts}}};")
    tex += ["\\end{axis}", "\\end{tikzpicture}"]
    (args.out / "budget.tex").write_text("\n".join(tex) + "\n")

    print(f"\n >> wrote {args.out / 'budget.csv'} and {args.out / 'budget.tex'}")
    print(" >> solid = accuracy on the true label; dashed = targeted attack success")


if __name__ == "__main__":
    main()
