"""
Download a VisualRWKV-v6 checkpoint (.pth) from the Hugging Face hub into the local
`ckpt/` directory. The vision tower (CLIP ViT-L/14@336) and the RWKV vocab are
NOT downloaded here: the CLIP weights come from `transformers` on first model load,
and the vocab is vendored under src/model/visual_rwkv/.

Usage:
    python scripts/download_visualrwkv.py            # default: 7B
    python scripts/download_visualrwkv.py 1b6        # smaller variant

Generated by AI
"""
import sys
from pathlib import Path

from huggingface_hub import hf_hub_download

PROJ = Path(__file__).resolve().parent.parent
# make `src` importable when run as `python scripts/download_visualrwkv.py`
sys.path.insert(0, str(PROJ))

from src.envvar import require_hf_token

OUT = PROJ / "ckpt"

REPO = "howard-hou/visualrwkv-6"

# variant -> checkpoint filename in the HF repo
CHECKPOINTS = {
    "7b": "VisualRWKV-v060-7B-v1.0-20240612.pth",
    "3b": "VisualRWKV-v060-3B-v1.0-20240612.pth",
    "1b6": "VisualRWKV-v060-1B6-v1.0-20240612.pth",
}


def download(variant: str) -> Path:
    filename = CHECKPOINTS[variant]
    dest = OUT / filename
    if dest.exists():
        print(f" >> {variant}: already present at {dest}, skipping")
        return dest
    OUT.mkdir(parents=True, exist_ok=True)
    print(f" >> {variant}: downloading {REPO}/{filename} -> {dest}")
    path = hf_hub_download(
        repo_id=REPO,
        filename=filename,
        local_dir=str(OUT),
        token=require_hf_token(),
    )
    print(f" >> {variant}: saved to {path}")
    return Path(path)


if __name__ == "__main__":
    variants = [v.lower() for v in sys.argv[1:]] or ["7b"]
    unknown = [v for v in variants if v not in CHECKPOINTS]
    if unknown:
        sys.exit(f"unknown variant(s): {unknown}; known: {list(CHECKPOINTS)}")
    for v in variants:
        download(v)
