"""
Validate VisualRWKV stateful decoding against the proven full-recompute path,
and measure the speedup. Run on a GPU (the WKV6 kernel is CUDA-only).

Checks:
  1. Per-step logits from forward_prefill + forward_step match the old
     forward_embeds full-recompute decode (same argmax tokens; small logit diff).
  2. Works for G>1 (batched, same-shape prompts) with the bidirectional image scan.
  3. New stateful decode is much faster than the full-recompute decode.

Generated by AI.
"""
import time
import torch

from src.model.visualrwkv import VisualRWKV
from src.model.visual_rwkv.model import STOP_TOKEN_INDEX

MODEL_PATH = "ckpt/VisualRWKV-v060-7B-v1.0-20240612.pth"
QUESTION = "Describe what you see and give detailed step-by-step instructions."
K = 48          # tokens to decode for the numeric comparison
SEED = 0


def build_prefix(vlm, G):
    # G copies of one prompt (equal shape) + G distinct random images
    img01 = torch.rand(G, 3, 336, 336, generator=torch.Generator().manual_seed(SEED)).to(vlm.device)
    pv = vlm._pixel_values(img01, "image01")
    before_ids, after_ids = vlm._prefix_ids(QUESTION, "")
    before = vlm.model.embed_tokens(torch.tensor([before_ids] * G, device=vlm.device))
    after = vlm.model.embed_tokens(torch.tensor([after_ids] * G, device=vlm.device))
    image_features = vlm.model.encode_images(pv.bfloat16().unsqueeze(1))
    x = torch.cat([before, image_features, after], dim=1)
    img_start = len(before_ids)
    img_end = img_start + image_features.shape[1] - 1
    return x, img_start, img_end, G


@torch.no_grad()
def ref_decode(vlm, x0, img_start, img_end, K):
    """Old path: re-run the whole sequence through forward_embeds every token."""
    x = x0.clone()
    G = x.shape[0]
    toks, hist = [[] for _ in range(G)], []
    for _ in range(K):
        logits = vlm.model.forward_embeds(x, img_start, img_end)[:, -1, :]
        hist.append(logits.float())
        nxt = logits.argmax(-1)
        for g in range(G):
            toks[g].append(int(nxt[g]))
        x = torch.cat([x, vlm.model.embed_tokens(nxt.unsqueeze(1))], dim=1)
    return toks, hist


@torch.no_grad()
def new_decode(vlm, x0, img_start, img_end, K, forced=None):
    """
    New path: prefill once, then single-token stateful steps.
    If `forced` (list of per-row token lists) is given, feed those tokens back instead
    of the model's own argmax -- teacher forcing that isolates numerical accuracy from
    greedy amplification. Otherwise free-run greedily.
    """
    logits, states = vlm.model.forward_prefill(x0, img_start, img_end)
    G = x0.shape[0]
    toks, hist = [[] for _ in range(G)], []
    cur = logits[:, -1, :]
    for t in range(K):
        hist.append(cur.float())
        nxt = cur.argmax(-1)
        for g in range(G):
            toks[g].append(int(nxt[g]))
        feed = nxt if forced is None else torch.tensor([forced[g][t] for g in range(G)], device=cur.device)
        tok_emb = vlm.model.embed_tokens(feed.unsqueeze(1))[:, 0, :]
        cur, states = vlm.model.forward_step(tok_emb, states)
    return toks, hist


def main():
    torch.manual_seed(SEED)
    vlm = VisualRWKV(device="auto", model_path=MODEL_PATH)

    for G in (1, 3):
        print(f"\n===== G = {G} =====")
        x0, img_start, img_end, _ = build_prefix(vlm, G)

        ref_toks, ref_hist = ref_decode(vlm, x0, img_start, img_end, K)
        # teacher-forced: feed ref tokens into the stateful path, compare logits step-by-step
        new_toks, new_hist = new_decode(vlm, x0, img_start, img_end, K, forced=ref_toks)

        any_nan = any(torch.isnan(n).any().item() for n in new_hist)
        per_step = [(r - n).abs().nan_to_num(nan=float("inf")).max().item()
                    for r, n in zip(ref_hist, new_hist)]
        # per-step argmax agreement under identical (teacher-forced) inputs
        agree = sum(int(new_toks[g][t] == ref_toks[g][t]) for g in range(G) for t in range(K))
        total = G * K
        print(f"  new logits contain NaN: {any_nan}")
        print(f"  teacher-forced logits max|diff|: {max(per_step):.4f}  (per-step[:8]: "
              f"{[round(d, 3) for d in per_step[:8]]})")
        print(f"  teacher-forced argmax agreement: {agree}/{total}")
        print(f"  ref[0] tokens: {ref_toks[0][:16]}")

    # ---- speed (G=4, K=128) ----
    G, KS = 4, 128
    x0, img_start, img_end, _ = build_prefix(vlm, G)
    torch.cuda.synchronize()
    t = time.perf_counter()
    ref_decode(vlm, x0, img_start, img_end, KS)
    torch.cuda.synchronize()
    ref_t = time.perf_counter() - t

    t = time.perf_counter()
    new_decode(vlm, x0, img_start, img_end, KS)
    torch.cuda.synchronize()
    new_t = time.perf_counter() - t
    print(f"\n===== speed (G={G}, K={KS}) =====")
    print(f"  full-recompute: {ref_t:6.2f}s   stateful: {new_t:6.2f}s   speedup: {ref_t / new_t:.1f}x")


if __name__ == "__main__":
    main()
