from typing import Any
from pathlib import Path
import torch
import gc
import os

from .utils import (
    load_yaml_config,
    save_yaml_config,
    save_json,
    seed_everything,
    tee_console,
    collect_environment,
)

from .model import VLM_factory


def run(args: list | dict[str, Any] | str | Path) -> Any:
    '''
    configuration structure:


    -   output_dir: ...
        task_type: ...
        ...

    -   ...
    -   ...
        

    '''

    print(" >> Experiment Top-level")

    if isinstance(args, (str, Path)):
        print(" >> Load configurations from", args)
        args = load_yaml_config(args)

    if isinstance(args, list):
        # iterate through all tasks
        for item in args:
            run(item)

    else:
        
        output_dir = Path(args['output_dir'])

        # we require to start from a fresh directory
        os.makedirs(output_dir, exist_ok=False)

        save_yaml_config(args, output_dir / "config.yaml")

        # mirror everything printed to stdout/stderr into the output folder
        with tee_console(output_dir / "console.log"):

            # execute a single task
            if args["task_type"] == "VLM-ImageClass":
                res = task_VLM_ImageClass(args)

            elif args["task_type"] == "VLM-ImageClass-attack":
                res = task_VLM_ImageClass_attack(args)

            else:
                raise ValueError("Invalid Config Type.")

            # sign a signature that the task is done
            with open(output_dir / "DONE", 'w') as p:
                p.write("THIS TASK FINISHED GRACEFULLY.")

        return res


def task_VLM_ImageClass(
    args: dict
):
    print(" >> Start VLM ImageClass Classification Task")

    from .model import VLM_factory
    from .bench import ImageClass_factory

    vlm_args = args['vlm']
    vlm = VLM_factory(vlm_args)

    imageclass_args = args['benchmark']
    imageclass = ImageClass_factory(imageclass_args)

    question = args['question']
    answer_priming = args['answer_priming']
    batch_size = args['batch_size']
    limit = args['limit']
    shuffle = args['shuffle']
    seed = args['seed']

    res = imageclass.eval_classify_lp(
        vlm,
        question,
        answer_priming,
        batch_size,
        limit,
        shuffle,
        seed
    )

    output_dir = Path(args['output_dir'])

    # split the result
    tensor_keys = ["indices", "preds", "correct_labels", "logprobs"]
    tensors = {k: res[k] for k in tensor_keys}
    summary = {k: v for k, v in res.items() if k not in tensor_keys}

    # readable summary
    save_json(summary, output_dir / "results.json")

    # per-example tensors for downstream analysis
    torch.save(tensors, output_dir / "tensors.pt")

    print(f" >> Saved results to {output_dir} (accuracy={res['accuracy']:.4f})")

    return res


def task_VLM_ImageClass_attack(
    args: dict
):
    '''
    Generated by AI
    '''
    print(" >> Start VLM ImageClass Attack Task.")

    from tqdm import tqdm
    from datasets import Dataset, Features, Array3D, Value, ClassLabel

    from .model import VLM_factory
    from .bench import ImageClass_factory
    from .image import IMAGE_SIZE

    vlm_args = args['vlm']
    vlm = VLM_factory(vlm_args)

    imageclass_args = args['benchmark']
    imageclass = ImageClass_factory(imageclass_args)

    question = args['question']
    answer_priming = args['answer_priming']
    batch_size = args['batch_size']
    limit = args['limit']
    shuffle = args['shuffle']
    seed = args['seed']

    # attack hyper-parameters (fall back to classify_attack_image01 defaults)
    attack_args = args.get('attack', {})
    max_steps = attack_args.get('max_steps', 20)
    stop_gap = attack_args.get('stop_gap', 0.5)
    gamma = attack_args.get('gamma', 1.0)
    lr = attack_args.get('lr', 0.003)

    # attack space: 'image01' (continuous) or 'resized' (snap to the uint8 grid via STE)
    attack_space = attack_args.get('space', 'image01')
    if attack_space not in ('image01', 'resized'):
        raise ValueError(f"attack.space must be 'image01' or 'resized', got {attack_space!r}")
    quantize = attack_space == 'resized'

    label_texts = imageclass.label_texts
    num_classes = len(label_texts)

    # one generator drives the random targets for the whole run -> reproducible given seed
    tgt_gen = torch.Generator().manual_seed(seed)

    n_eval = limit if limit is not None else None
    n_batches = None
    if n_eval is not None:
        n_batches = (n_eval + batch_size - 1) // batch_size   # ceil, for tqdm only

    orig_images, adv_images = [], []
    orig_labels, attack_labels, all_indices = [], [], []

    for image01, labels, indices in tqdm(
        imageclass.loader(batch_size=batch_size, limit=limit, shuffle=shuffle, seed=seed),
        total=n_batches, desc="attack"
    ):
        B = labels.shape[0]

        # pick a uniformly random target class different from the true label
        rand = torch.randint(0, num_classes - 1, (B,), generator=tgt_gen)
        targets = rand + (rand >= labels).long()   # shift past the true label -> never equal

        adv_image01 = vlm.classify_attack(
            image01s=image01.to(vlm.device),
            question=question,
            answer_priming=answer_priming,
            candidates=label_texts,
            target_candidate=targets.tolist(),
            max_steps=max_steps,
            stop_gap=stop_gap,
            gamma=gamma,
            lr=lr,
            quantize=quantize,
        ).detach().cpu()

        # store the raw image01 float tensors (C, H, W) in [0, 1]; converting back to
        # uint8 images would round away the adversarial perturbation
        orig_images.extend(image01.float().numpy())
        adv_images.extend(adv_image01.float().numpy())
        orig_labels.extend(labels.tolist())
        attack_labels.extend(targets.tolist())
        all_indices.extend(indices.tolist())

    # pack the per-example results into a HuggingFace dataset
    features = Features({
        "index": Value("int64"),
        "original_image": Array3D(shape=(3, IMAGE_SIZE, IMAGE_SIZE), dtype="float32"),
        "adversarial_image": Array3D(shape=(3, IMAGE_SIZE, IMAGE_SIZE), dtype="float32"),
        "original_label": ClassLabel(names=label_texts),
        "attack_label": ClassLabel(names=label_texts),
    })
    ds = Dataset.from_dict(
        {
            "index": all_indices,
            "original_image": orig_images,
            "adversarial_image": adv_images,
            "original_label": orig_labels,
            "attack_label": attack_labels,
        },
        features=features,
    )

    output_dir = Path(args['output_dir'])

    ds.save_to_disk(str(output_dir / "dataset"))

    summary = {
        "task_type": "VLM-ImageClass-attack",
        "question": question,
        "answer_priming": answer_priming,
        "batch_size": batch_size,
        "limit": limit,
        "shuffle": shuffle,
        "seed": seed,
        "labels": label_texts,
        "num_examples": len(all_indices),
        "attack": {
            "space": attack_space,
            "max_steps": max_steps,
            "stop_gap": stop_gap,
            "gamma": gamma,
            "lr": lr,
            "target": "random-other-class",
        },
    }

    # readable summary
    save_json(summary, output_dir / "results.json")

    # per-example bookkeeping tensors (row-aligned with the dataset)
    torch.save(
        {
            "indices": torch.tensor(all_indices),
            "original_labels": torch.tensor(orig_labels),
            "attack_labels": torch.tensor(attack_labels),
        },
        output_dir / "tensors.pt",
    )

    res = {**summary, "dataset": ds}

    print(f" >> Saved attack dataset to {output_dir} ({len(all_indices)} examples)")

    return res